name: backport

on:
  pull_request_target:
    types: ["labeled", "closed"]

permissions:
  contents: write
  pull-requests: write

jobs:
  backport:
    name: Backport PR to branch specified by pr label(s) 'backport-[branch name]'
    if: |
      github.event.pull_request.merged == true
      && contains(join(github.event.pull_request.labels.*.name, ','), 'backport-')
      && (
        (github.event.action == 'labeled' && startsWith(github.event.label.name, 'backport-'))
        || (github.event.action == 'closed')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Backport Action
        id: backport # Give the step an ID to reference its outputs
        uses: sorenlouv/backport-github-action@ad888e978060bc1b2798690dd9d03c4036560947 # v9.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_backport_label_prefix: backport-
          add_original_reviewers: true
      - name: Info log
        if: ${{ success() }}
        run: cat ~/.backport/backport.info.log

      - name: Debug log
        if: ${{ failure() }}
        run: cat ~/.backport/backport.debug.log

      - name: Add Specific Labels to Backport PR
        # Only run if the backport step successfully created a PR
        if: steps.backport.outputs.backport_pull_request_number != ''
        uses: actions-ecosystem/action-add-labels@v1 # Example labelling action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.backport.outputs.backport_pull_request_number }}
          labels: | # Your desired arbitrary labels
            my-custom-label
            auto-backport