name: backport

on:
  pull_request_target:
    branches:
      - 8.x
    types:
      - opened

permissions:
  contents: write
  pull-requests: write

jobs:
  backport:
    name: Merge backport PR to 8.x
    runs-on: ubuntu-latest
    steps:
      - name: Get Pull Request Number
        id: get_pr_number
        run: echo "PR_NUMBER=$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)" >> $GITHUB_ENV

      - name: Mask GitHub Token
        run: |
          echo "::add-mask::${{ secrets.GITHUB_TOKEN }}"
          echo "${{ secrets.GITHUB_TOKEN }}"

      - name: Merge Pull Request
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PR_NUMBER }}/merge \
            -d '{"merge_method":"merge"}'
            curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ::add-mask::${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PR_NUMBER }}/merge \
            -d '{"merge_method":"merge"}'
