name: backport

on:
  pull_request_target:
    types: ["labeled", "closed"]

permissions:
  contents: write
  pull-requests: write

jobs:
  backport:
    name: Backport PR to 8.x
    if: |
      github.event.pull_request.merged == true
      && contains(github.event.pull_request.labels.*.name, 'backport-8.x')
      && (
        (github.event.action == 'labeled' && github.event.label.name == 'backport-8.x')
        || (github.event.action == 'closed')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Backport Action
        uses: intxgo/backport-github-action@57cfc20d9d51f7816f9fe5003cff93cb883185d8 # v9.5.1_with_auto_merge
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_backport_label_prefix: backport-
          add_original_reviewers: true
          auto_merge: true

      - name: Info log
        if: ${{ success() }}
        run: cat ~/.backport/backport.info.log

      - name: Debug log
        if: ${{ failure() }}
        run: cat ~/.backport/backport.debug.log
