name: Enforce Fast-Forward and Merge Order

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '8.x'

jobs:
  check-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check all commits are present in main
        run: |
          # Fetch the latest commits from the main branch
          git fetch origin main

          # Get the list of commits in the main branch
          main_commits=$(git rev-list origin/main --max-count=100)
          echo "main commits:\n $main_commits"

          # Get the list of commits in the backport branch
          # It should be only one, since we always squash
          # anyway if someone tries to add something it'll land on the top
          backport_commits=$(git rev-list HEAD --max-count=10)
          echo "backport commits:\n $backport_commits"

          # Check if the commits in the backport branch are in main branch
          for commit in $backport_commits; do
            if ! echo "$main_commits" | grep -q "$commit"; then
              echo "Commit $commit is not in the main branch"
              exit 1
            fi
          done

          echo "All commits are validated. PR is ready for fast-forward merge"
